### ISSUE TITLE
It doesn't download any files - Please help

### ISSUE THREAD

**Issue by KatieBelli** [uhwot/orpheusdl-deezer#1]
I put it to the module folder (original OrpheusDL).
Entered:
C:\Users\...\Downloads\orpheusdl-master>python orpheus.py

Result: "New settings detected, or the configuration has been reset. Please update settings.json"

Had no issue with using the TIDAL module so far. But I'm stuck with Deezer module.

![Issue](https://user-images.githubusercontent.com/109644887/180192715-37999670-2fb5-46b3-8450-203d1ad9a2df.PNG)

I have a Deezer subscription (Free Trial). How can I solve this?

**Comment by uhwot** [comment]
@KatieBelli Looks like you didn't set the keys needed in the settings (track_url_key and bf_secret)
They're in this telegram group on the pinned message: https://t.me/orpheusdl

**Comment by KatieBelli** [comment]
> @KatieBelli Looks like you didn't set the keys needed in the settings (track_url_key and bf_secret) They're in this telegram group on the pinned message: https://t.me/orpheusdl

Wanted to close this as "Solved" and say thank you. :)
